---
# Sonarr - TV show management

- name: Create Sonarr stack directory
  ansible.builtin.file:
    path: "{{ media_services_stacks_dir }}/sonarr/config"
    state: directory
    mode: "0755"

- name: Deploy Sonarr docker-compose.yml
  ansible.builtin.copy:
    dest: "{{ media_services_stacks_dir }}/sonarr/docker-compose.yml"
    content: |
      services:
        sonarr:
          image: lscr.io/linuxserver/sonarr:latest
          container_name: sonarr
          restart: unless-stopped
          ports:
            - "{{ media_services_sonarr_port }}:8989"
          environment:
            - PUID={{ media_services_puid }}
            - PGID={{ media_services_pgid }}
            - TZ={{ media_services_timezone }}
          volumes:
            - ./config:/config
            - {{ media_services_nfs_mount }}/tv:/tv
            - {{ media_services_nfs_mount }}/documentaries:/documentaries
            - {{ media_services_nfs_mount }}/downloads:/downloads
    mode: "0644"

- name: Start Sonarr stack
  ansible.builtin.command:
    cmd: docker compose up -d
    chdir: "{{ media_services_stacks_dir }}/sonarr"
  register: sonarr_start
  changed_when: "'Started' in sonarr_start.stderr or 'Created' in sonarr_start.stderr"
