$ANSIBLE_VAULT;1.1;AES256
35643232646335303664333837643063396537616336626261636265623361643539353033323134
6464356463316237626664353734386234353132326662390a376638376263626165663965336238
33333161316138663532623638393863643235393537626538383164353666343138333839613163
3330326339336230650a396265613165623566336338313232303338306139303536353763346266
62313666623063666131313365303331393361346233646136363064313966316233363835626361
64386233396639353033366466333363316531666330306535303537613863666266636332643032
61303637366336373339313866313463633734323439383361626535366235346330306639656231
36363635633163313962343062336562313661326233306531633066393566623935316537343662
37383564323664303464343065313363393733363566386534643136336530636563656534376636
36333531313562343939306233666137383665373338613231326639306162393630326264373436
39303632666461326130383631613039646238353166666364346135383731373333316565666264
63313637363964373232323539646164363838353436623939376539373730373137356633383864
37363833306230643235653939646663613330393831346562333562383339333366636431353937
31663839323262363532323832336163643561623261353466313261373762353634626666643439
34303565373164653633376664626665623363356662626136343530383062343262653562306533
39613165316163623430336632326337353537323963323462633439633234393234653738643438
63363434363365366364326632333136356330343236326130646431376661663464333035663631
33666466363339643463333138646564613034643639356366373236393937646135643830353537
31336639396133353833343531386435333664303133356438303465376636336236386638653862
31643062666262623432383363346435333139653636336664636331636338383932356566626430
39376238643530333165383739393636663730363466336663633563626164363837613830316265
3662323635306462323263346131616139633462376235666630
