$ANSIBLE_VAULT;1.1;AES256
36346566393364613466356164303466306562386461316566393536346239333537326665646431
3365346565653432626137366465303537333466663439300a363638303466633830333134666337
38343834333633383138313931323462653733356332643233386139333838623235303238346230
3238356335383562660a363534653538383564616537376565643264346334613134386137636539
35333061643731326234376537323234306161336239623839636330306365623836633631343861
63386666626262346437363630386135313838303364316661303733373364633934633839326133
63613465366164383663316137653039643633656131383132373264616539663963623839376530
33613363376563333532353666613631303831666432353634386662316133653562313865663439
35666335633432393861616330396337333437663565646336643237376132653230363434626438
63353463343439666435386435373266326562313036346466323464363161323262646663346635
30373365386138623039653466353562333865366332653166666234643763363631306261303535
62373935393039643936356435666532343563393236373738653463666632326331386464346239
3536
