$ANSIBLE_VAULT;1.1;AES256
32346334393231613735306339353165316537656561373339613032363633633730383763353336
3436663537346333383864383239353265373233313563390a326363656264356330643435326565
33343837393039326363376336363566363035626537346638616531313338323734663466376261
6434336130376134640a663766653865633234663034303566343932393564363631353536363331
35303038393433393038376266303832366462356362346532646136636335396532373039363661
32336236333666343436393963633834656562393962303633663430383136383035623539373533
62336638393263616437383635623534646265313466623733663938663466653235323862643531
30393664623664313765316531373932316364343361396336383939303565623266353132363737
34663062353930376333346438613339376330633861623731666537363962353435323763383562
33333038626261323862393637323363393765396634313431623763363064353036386232653362
35663861373163636432646262383264343039343437346134373937653238663330373231336337
31666136623465303930396666333164326333366530313264323962333038386463356266396666
32323137656362326438306664376233386661616434346235333632336164666364663736353734
31333561343730633933303863363962633331363335323538623134396665656130323465353765
613731326363623431663761316462343562
