---
# Global variables for all hosts

# SSH configuration
ssh_authorized_keys:
  - "sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAIAbJvERLxQAbXMZDvuPqNNTvrhLj+HLUdvWdGhf/QA/0AAAABHNzaDo= PC Key"

# Timezone (adjust as needed)
timezone: "Europe/Berlin"
